### ISSUE TITLE
Fix octokit deprecation warnings

### ISSUE THREAD

**Issue by wilhelmklopp** [integrations/slack#808]
When running the [tests at the moment](https://travis-ci.org/integrations/slack/builds/501553272?utm_source=github_status&utm_medium=notification), you'll find lots of Octokit deprecation warnings. We'll want to udpate these so that we no longer use any deprecated methods.

<details>

```
PASS  test/integration/notifications.test.js (46.584s)
  ● Console

    console.warn node_modules/@octokit/rest/lib/deprecate.js:10
      DEPRECATED (@octokit/rest): `pullRequests.getReviews()` is deprecated, use `pullRequests.listReviews()`

 PASS  test/integration/list-subscriptions.test.js (11.04s)
 PASS  test/messages/pull-request.test.js
 PASS  test/messages/deployment-status.test.js
 PASS  test/messages/Issue.test.js
 PASS  test/messages/user-settings/index.test.js
 PASS  test/messages/abstract-issue.test.js
 PASS  test/messages/Comment.test.js
 PASS  test/messages/Blob.test.js
 PASS  test/messages/Message.test.js
 PASS  test/helpers.test.js
 PASS  test/github-url.test.js
 PASS  test/messages/Review.test.js
 PASS  test/messages/push.test.js
 PASS  test/messages/user-settings/unfurl-auto-settings-for-repo.test.js
 PASS  test/messages/Account.test.js
 PASS  test/messages/Repository.test.js
 PASS  test/messages/Status.test.js
 PASS  test/messages/Ref.test.js
 PASS  test/support-link.test.js
 PASS  test/cache.test.js
 PASS  test/messages/unfurls/auto-unfurl-setting-confirm.test.js
 PASS  test/messages/repository-deleted.test.js
 PASS  test/messages/subscription-list.test.js
 PASS  test/messages/flow/re-enable-multiple-subscriptions.test.js
 PASS  test/messages/unfurls/mute-prompts-setting-confirm.test.js
 PASS  test/messages/unfurls/auto-unfurl-prompt.test.js
 PASS  test/messages/flow/exception.test.js
 PASS  test/messages/unfurls/private-unfurl-prompt.test.js
 PASS  test/integration/github-app-authorization-revoked.test.js (7.38s)
 PASS  test/integration/slack-uninstall.test.js
 PASS  test/messages/flow/slack-installed.test.js
 PASS  test/messages/flow/help.test.js
 PASS  test/messages/flow/error-message.test.js
 PASS  test/messages/unfurls/PromptSignIn.test.js
 PASS  test/messages/flow/sign-in-confirm.test.js
 PASS  test/messages/user-settings/unfurl-auto-settings-remove-confirm.test.js
 PASS  test/messages/unfurls/unfurls-disabled-error.test.js
 PASS  test/messages/unfurls/mute-prompts-prompt.test.js
 PASS  test/messages/user-settings/unfurl-settings-unmute-confirm.test.js
 PASS  test/messages/Public.test.js
12:50:51.925Z ERROR http: A request error occurred: ENETUNREACH (id=50580aa0-c10d-4670-85b6-41136eb10863)
  Error: A request error occurred: ENETUNREACH
      at requestErrorWithOriginal (/Users/wilhelmklopp/workspace/integrations/slack/node_modules/@slack/client/src/WebClient.ts:681:5)
      at got.post.catch (/Users/wilhelmklopp/workspace/integrations/slack/node_modules/@slack/client/src/WebClient.ts:145:21)
      at process.internalTickCallback (internal/process/next_tick.js:77:7)
 PASS  test/integration/unfurl.test.js (12.536s)
  ● Console

    console.warn node_modules/@octokit/rest/lib/deprecate.js:10
      DEPRECATED (@octokit/rest): `users.getForUser()` is deprecated, use `users.getByUsername()`
    console.warn node_modules/@octokit/rest/lib/deprecate.js:10
      DEPRECATED (@octokit/rest): `users.get()` is deprecated, use `users.getAuthenticated()`

(node:95593) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
 PASS  test/integration/subscriptions.test.js (11.196s)
  ● Console

    console.warn node_modules/@octokit/rest/lib/deprecate.js:10
      DEPRECATED (@octokit/rest): `users.getForUser()` is deprecated, use `users.getByUsername()`

 PASS  test/integration/create.test.js
  ● Console

    console.warn node_modules/@octokit/rest/lib/deprecate.js:10
      DEPRECATED (@octokit/rest): `issues.getLabels()` is deprecated, use `issues.listLabelsForRepo()`
    console.warn node_modules/@octokit/rest/lib/deprecate.js:10
      DEPRECATED (@octokit/rest): `repos.getContent()` is deprecated, use `repos.getContents()`
    console.warn node_modules/@octokit/rest/lib/deprecate.js:10
      DEPRECATED (@octokit/rest): `apps.get()` is deprecated, use `apps.getAuthenticated()`

 PASS  test/integration/signin.test.js
  ● Console

    console.warn node_modules/@octokit/rest/lib/deprecate.js:10
      DEPRECATED (@octokit/rest): `users.get()` is deprecated, use `users.getAuthenticated()`
    console.warn node_modules/@octokit/rest/lib/deprecate.js:10
      DEPRECATED (@octokit/rest): `users.getForUser()` is deprecated, use `users.getByUsername()`
    console.warn node_modules/@octokit/rest/lib/deprecate.js:10
      DEPRECATED (@octokit/rest): `apps.get()` is deprecated, use `apps.getAuthenticated()`

 PASS  test/integration/signout.test.js
  ● Console

    console.warn node_modules/@octokit/rest/lib/deprecate.js:10
      DEPRECATED (@octokit/rest): `users.get()` is deprecated, use `users.getAuthenticated()`

 PASS  test/integration/issue-state.test.js
  ● Console

    console.warn node_modules/@octokit/rest/lib/deprecate.js:10
      DEPRECATED (@octokit/rest): `users.get()` is deprecated, use `users.getAuthenticated()`
    console.warn node_modules/@octokit/rest/lib/deprecate.js:10
      DEPRECATED (@octokit/rest): `issues.edit()` is deprecated, use `issues.update()`

 PASS  test/integration/deployment.test.js
  ● Console

    console.warn node_modules/@octokit/rest/lib/deprecate.js:10
      DEPRECATED (@octokit/rest): `repos.getBranches()` is deprecated, use `repos.listBranches()`
```

</details>

**Comment by wilhelmklopp** [comment]
This should be fixed as of #857 🙌
